import { nowIso } from '@/lib/id'
import type { JobOpening, Candidate, Interview } from './types'

export function openingsSeed(): JobOpening[] {
  const now = nowIso()
  return [
    {
      id: 'jo-001',
      title: { en: 'Senior Frontend Engineer', ar: 'مهندس واجهات أمامية أول' },
      departmentId: 'dept-eng',
      positionId: 'pos-fe-snr',
      description: 'Build and lead our React-based product surfaces.',
      requirements:
        '5+ years of React, TypeScript, Tailwind, accessibility experience',
      status: 'open',
      postedAt: '2026-04-01',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'jo-002',
      title: { en: 'Backend Engineer', ar: 'مهندس خلفية' },
      departmentId: 'dept-eng',
      positionId: 'pos-be-mid',
      description: 'Own backend services for our HR platform.',
      requirements: 'Node.js, PostgreSQL, REST/GraphQL',
      status: 'open',
      postedAt: '2026-04-10',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'jo-003',
      title: { en: 'Marketing Specialist', ar: 'أخصائي تسويق' },
      departmentId: 'dept-mkt',
      positionId: 'pos-mkt',
      description: 'Run our digital marketing programs.',
      requirements: 'Performance marketing, SEO, copywriting',
      status: 'open',
      postedAt: '2026-04-15',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'jo-004',
      title: { en: 'Accountant', ar: 'محاسب' },
      departmentId: 'dept-fin',
      positionId: 'pos-acc',
      description: 'Daily accounting and reconciliations.',
      requirements: 'CPA preferred, ERP experience',
      status: 'closed',
      postedAt: '2026-01-05',
      closedAt: '2026-03-01',
      createdAt: now,
      updatedAt: now,
    },
  ]
}

export function candidatesSeed(): Candidate[] {
  const now = nowIso()
  return [
    {
      id: 'cand-001',
      firstName: 'Faris',
      lastName: 'Al-Rashed',
      email: 'faris@example.com',
      phone: '+966 55 100 1001',
      jobOpeningId: 'jo-001',
      stage: 'interview',
      appliedAt: '2026-04-05',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-002',
      firstName: 'Reema',
      lastName: 'Al-Najjar',
      email: 'reema@example.com',
      phone: '+966 55 100 1002',
      jobOpeningId: 'jo-001',
      stage: 'screening',
      appliedAt: '2026-04-08',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-003',
      firstName: 'Bandar',
      lastName: 'Al-Hajri',
      email: 'bandar@example.com',
      phone: '+966 55 100 1003',
      jobOpeningId: 'jo-002',
      stage: 'applied',
      appliedAt: '2026-04-12',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-004',
      firstName: 'Mona',
      lastName: 'Al-Subaie',
      email: 'mona@example.com',
      phone: '+966 55 100 1004',
      jobOpeningId: 'jo-002',
      stage: 'offer',
      appliedAt: '2026-04-02',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-005',
      firstName: 'Tariq',
      lastName: 'Al-Anzi',
      email: 'tariq@example.com',
      phone: '+966 55 100 1005',
      jobOpeningId: 'jo-003',
      stage: 'applied',
      appliedAt: '2026-04-18',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-006',
      firstName: 'Salma',
      lastName: 'Al-Ahmadi',
      email: 'salma@example.com',
      phone: '+966 55 100 1006',
      jobOpeningId: 'jo-001',
      stage: 'rejected',
      appliedAt: '2026-04-04',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'cand-007',
      firstName: 'Ibrahim',
      lastName: 'Al-Sulaiman',
      email: 'ibrahim@example.com',
      phone: '+966 55 100 1007',
      jobOpeningId: 'jo-004',
      stage: 'hired',
      appliedAt: '2026-01-15',
      createdAt: now,
      updatedAt: now,
    },
  ]
}

export function interviewsSeed(): Interview[] {
  const now = nowIso()
  return [
    {
      id: 'int-001',
      candidateId: 'cand-001',
      interviewerId: 'emp-002',
      scheduledAt: '2026-04-28T10:00:00Z',
      type: 'video',
      result: 'pending',
      notes: 'Technical screen scheduled',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'int-002',
      candidateId: 'cand-002',
      interviewerId: 'emp-001',
      scheduledAt: '2026-04-26T14:00:00Z',
      type: 'phone',
      result: 'pass',
      notes: 'Strong communication, advance to next round',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'int-003',
      candidateId: 'cand-004',
      interviewerId: 'emp-002',
      scheduledAt: '2026-04-15T11:00:00Z',
      type: 'onsite',
      result: 'pass',
      notes: 'Excellent system design discussion',
      createdAt: now,
      updatedAt: now,
    },
  ]
}
