import { nowIso } from '@/lib/id'
import type { Employee } from './types'

export function employeesSeed(): Employee[] {
  const now = nowIso()
  const base = {
    createdAt: now,
    updatedAt: now,
  }
  return [
    {
      ...base,
      id: 'emp-001',
      employeeNumber: 'EMP-001',
      firstName: { en: 'Sarah', ar: 'سارة' },
      lastName: { en: 'Al-Qahtani', ar: 'القحطاني' },
      email: 'sarah.q@company.com',
      phone: '+966 50 111 2233',
      departmentId: 'dept-hr',
      positionId: 'pos-hr-spec',
      branchId: 'br-riyadh',
      hireDate: '2020-03-15',
      employmentType: 'full-time',
      status: 'active',
      nationalId: '1098765432',
      dateOfBirth: '1990-05-22',
      gender: 'female',
      maritalStatus: 'married',
      address: 'Al Olaya, Riyadh',
      salary: 14000,
    },
    {
      ...base,
      id: 'emp-002',
      employeeNumber: 'EMP-002',
      firstName: { en: 'Mohammed', ar: 'محمد' },
      lastName: { en: 'Al-Harbi', ar: 'الحربي' },
      email: 'mohammed.h@company.com',
      phone: '+966 55 333 4455',
      departmentId: 'dept-eng',
      positionId: 'pos-eng-lead',
      branchId: 'br-riyadh',
      hireDate: '2019-01-08',
      employmentType: 'full-time',
      status: 'active',
      nationalId: '1023456789',
      dateOfBirth: '1985-11-12',
      gender: 'male',
      maritalStatus: 'married',
      address: 'Al Malqa, Riyadh',
      salary: 35000,
    },
    {
      ...base,
      id: 'emp-003',
      employeeNumber: 'EMP-003',
      firstName: { en: 'Fatima', ar: 'فاطمة' },
      lastName: { en: 'Al-Shehri', ar: 'الشهري' },
      email: 'fatima.s@company.com',
      phone: '+966 53 555 6677',
      departmentId: 'dept-eng',
      positionId: 'pos-fe-snr',
      managerId: 'emp-002',
      branchId: 'br-riyadh',
      hireDate: '2021-06-20',
      employmentType: 'full-time',
      status: 'active',
      nationalId: '1056781234',
      dateOfBirth: '1992-08-30',
      gender: 'female',
      maritalStatus: 'single',
      address: 'Al Rabwah, Riyadh',
      salary: 22000,
    },
    {
      ...base,
      id: 'emp-004',
      employeeNumber: 'EMP-004',
      firstName: { en: 'Ahmed', ar: 'أحمد' },
      lastName: { en: 'Al-Ghamdi', ar: 'الغامدي' },
      email: 'ahmed.g@company.com',
      phone: '+966 56 777 8899',
      departmentId: 'dept-eng',
      positionId: 'pos-be-mid',
      managerId: 'emp-002',
      branchId: 'br-jeddah',
      hireDate: '2022-02-14',
      employmentType: 'full-time',
      status: 'active',
      nationalId: '1078901234',
      dateOfBirth: '1994-04-18',
      gender: 'male',
      maritalStatus: 'single',
      address: 'Al Hamra, Jeddah',
      salary: 17500,
    },
    {
      ...base,
      id: 'emp-005',
      employeeNumber: 'EMP-005',
      firstName: { en: 'Noura', ar: 'نورة' },
      lastName: { en: 'Al-Otaibi', ar: 'العتيبي' },
      email: 'noura.o@company.com',
      phone: '+966 50 999 1122',
      departmentId: 'dept-fin',
      positionId: 'pos-acc',
      branchId: 'br-riyadh',
      hireDate: '2020-09-01',
      employmentType: 'full-time',
      status: 'active',
      nationalId: '1090123456',
      dateOfBirth: '1991-12-05',
      gender: 'female',
      maritalStatus: 'married',
      address: 'Al Sulaymaniah, Riyadh',
      salary: 11500,
    },
    {
      ...base,
      id: 'emp-006',
      employeeNumber: 'EMP-006',
      firstName: { en: 'Khalid', ar: 'خالد' },
      lastName: { en: 'Al-Dosari', ar: 'الدوسري' },
      email: 'khalid.d@company.com',
      phone: '+966 55 222 3344',
      departmentId: 'dept-sales',
      positionId: 'pos-sales-mgr',
      branchId: 'br-jeddah',
      hireDate: '2018-07-15',
      employmentType: 'full-time',
      status: 'active',
      nationalId: '1012345670',
      dateOfBirth: '1983-09-25',
      gender: 'male',
      maritalStatus: 'married',
      address: 'Al Salamah, Jeddah',
      salary: 21000,
    },
    {
      ...base,
      id: 'emp-007',
      employeeNumber: 'EMP-007',
      firstName: { en: 'Laila', ar: 'ليلى' },
      lastName: { en: 'Al-Mutairi', ar: 'المطيري' },
      email: 'laila.m@company.com',
      phone: '+966 53 444 5566',
      departmentId: 'dept-mkt',
      positionId: 'pos-mkt',
      branchId: 'br-riyadh',
      hireDate: '2023-04-10',
      employmentType: 'full-time',
      status: 'on-leave',
      nationalId: '1034567890',
      dateOfBirth: '1996-02-14',
      gender: 'female',
      maritalStatus: 'single',
      address: 'Al Yasmin, Riyadh',
      salary: 9000,
    },
    {
      ...base,
      id: 'emp-008',
      employeeNumber: 'EMP-008',
      firstName: { en: 'Yousef', ar: 'يوسف' },
      lastName: { en: 'Al-Zahrani', ar: 'الزهراني' },
      email: 'yousef.z@company.com',
      phone: '+966 56 666 7788',
      departmentId: 'dept-ops',
      positionId: 'pos-ops',
      branchId: 'br-dxb',
      hireDate: '2022-11-22',
      employmentType: 'full-time',
      status: 'active',
      nationalId: '1067890123',
      dateOfBirth: '1989-06-03',
      gender: 'male',
      maritalStatus: 'married',
      address: 'JLT, Dubai',
      salary: 10000,
    },
    {
      ...base,
      id: 'emp-009',
      employeeNumber: 'EMP-009',
      firstName: { en: 'Hala', ar: 'هلا' },
      lastName: { en: 'Al-Faisal', ar: 'الفيصل' },
      email: 'hala.f@company.com',
      phone: '+966 50 111 9988',
      departmentId: 'dept-eng',
      positionId: 'pos-be-mid',
      managerId: 'emp-002',
      branchId: 'br-riyadh',
      hireDate: '2024-01-15',
      employmentType: 'contract',
      status: 'active',
      nationalId: '1045678901',
      dateOfBirth: '1995-10-19',
      gender: 'female',
      maritalStatus: 'single',
      address: 'Al Nakheel, Riyadh',
      salary: 16000,
    },
    {
      ...base,
      id: 'emp-010',
      employeeNumber: 'EMP-010',
      firstName: { en: 'Omar', ar: 'عمر' },
      lastName: { en: 'Al-Saud', ar: 'السعود' },
      email: 'omar.s@company.com',
      phone: '+966 55 888 9900',
      departmentId: 'dept-eng',
      positionId: 'pos-fe-snr',
      managerId: 'emp-002',
      branchId: 'br-riyadh',
      hireDate: '2025-09-01',
      employmentType: 'intern',
      status: 'active',
      nationalId: '1089012345',
      dateOfBirth: '2002-01-10',
      gender: 'male',
      maritalStatus: 'single',
      address: 'Al Wurud, Riyadh',
      salary: 5000,
    },
  ]
}
