import { nowIso } from '@/lib/id'
import type { Position } from './types'

export function positionsSeed(): Position[] {
  const now = nowIso()
  return [
    {
      id: 'pos-fe-snr',
      title: { en: 'Senior Frontend Engineer', ar: 'مهندس واجهات أمامية أول' },
      departmentId: 'dept-eng',
      level: 'senior',
      description: 'React/TypeScript expert',
      minSalary: 18000,
      maxSalary: 28000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'pos-be-mid',
      title: { en: 'Backend Engineer', ar: 'مهندس خلفية' },
      departmentId: 'dept-eng',
      level: 'mid',
      description: 'Node.js / databases',
      minSalary: 14000,
      maxSalary: 22000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'pos-eng-lead',
      title: { en: 'Engineering Lead', ar: 'قائد فريق هندسي' },
      departmentId: 'dept-eng',
      level: 'lead',
      description: 'Team leadership and architecture',
      minSalary: 28000,
      maxSalary: 42000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'pos-hr-spec',
      title: { en: 'HR Specialist', ar: 'أخصائي موارد بشرية' },
      departmentId: 'dept-hr',
      level: 'mid',
      description: 'Recruitment and employee relations',
      minSalary: 10000,
      maxSalary: 15000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'pos-acc',
      title: { en: 'Accountant', ar: 'محاسب' },
      departmentId: 'dept-fin',
      level: 'mid',
      description: 'Financial accounting',
      minSalary: 9000,
      maxSalary: 14000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'pos-sales-mgr',
      title: { en: 'Sales Manager', ar: 'مدير مبيعات' },
      departmentId: 'dept-sales',
      level: 'senior',
      description: 'Lead a sales territory',
      minSalary: 16000,
      maxSalary: 26000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'pos-mkt',
      title: { en: 'Marketing Specialist', ar: 'أخصائي تسويق' },
      departmentId: 'dept-mkt',
      level: 'junior',
      description: 'Digital marketing campaigns',
      minSalary: 7000,
      maxSalary: 11000,
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'pos-ops',
      title: { en: 'Operations Coordinator', ar: 'منسق عمليات' },
      departmentId: 'dept-ops',
      level: 'mid',
      description: 'Coordinate operational processes',
      minSalary: 8000,
      maxSalary: 12000,
      createdAt: now,
      updatedAt: now,
    },
  ]
}
